development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: cash_out
  username: postgres
  password: resolve
  pool: 5
  encoding: utf8

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: cash_out_test
  username: postgres
  password: resolve
  pool: 5
  encoding: utf8